swagger: "2.0"
info:
    title: Signer Service
    description: Signer service exposes HTTP API for making and verifying digital signatures and proofs for Verifiable Credentials.
    version: 0.0.1
host: localhost:8085
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /liveness:
        get:
            tags:
                - health
            summary: Liveness health
            operationId: health#Liveness
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthResponse'
                        required:
                            - service
                            - status
                            - version
            schemes:
                - http
    /readiness:
        get:
            tags:
                - health
            summary: Readiness health
            operationId: health#Readiness
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthResponse'
                        required:
                            - service
                            - status
                            - version
            schemes:
                - http
    /v1/credential:
        post:
            tags:
                - signer
            summary: CreateCredential signer
            description: CreateCredential creates VC with proof from raw JSON data.
            operationId: signer#CreateCredential
            parameters:
                - name: x-origin
                  in: header
                  description: Origin of call
                  required: true
                  type: string
                - name: x-tenantid
                  in: header
                  description: tenantid
                  required: true
                  type: string
                - name: x-groupid
                  in: header
                  description: Tenant Group
                  required: false
                  type: string
                  default: ""
                - name: CreateCredentialRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/CreateCredentialRequest'
                    required:
                        - namespace
                        - key
                        - credentialSubject
            responses:
                "200":
                    description: OK response.
                    schema: {}
            schemes:
                - http
    /v1/credential/proof:
        post:
            tags:
                - signer
            summary: CredentialProof signer
            description: CredentialProof adds a proof to a given Verifiable Credential.
            operationId: signer#CredentialProof
            parameters:
                - name: CredentialProofRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/CredentialProofRequest'
                    required:
                        - namespace
                        - key
                        - credential
                        - x-tenantid
                        - x-did
                        - x-origin
            responses:
                "200":
                    description: OK response.
                    schema: {}
            schemes:
                - http
    /v1/credential/verify:
        post:
            tags:
                - signer
            summary: VerifyCredential signer
            description: VerifyCredential verifies the proof of a Verifiable Credential.
            operationId: signer#VerifyCredential
            parameters:
                - name: x-format
                  in: header
                  description: format
                  required: false
                  type: string
                  default: ldp_vc
                  enum:
                    - ldp_vc
                    - dc+sd-jwt
                - name: x-namespace
                  in: header
                  description: Namespace for status check
                  required: true
                  type: string
                - name: x-group
                  in: header
                  description: Group for status check
                  required: false
                  type: string
                - name: x-tenantid
                  in: header
                  description: tenantid
                  required: false
                  type: string
                - name: x-groupid
                  in: header
                  description: Group
                  required: false
                  type: string
                - name: VerifyCredentialRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VerifyCredentialRequest'
                    required:
                        - credential
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/VerifyResult'
                        required:
                            - valid
            schemes:
                - http
    /v1/did/configuration:
        get:
            tags:
                - signer
            summary: DidConfiguration signer
            description: Creates did configuration.
            operationId: signer#DidConfiguration
            parameters:
                - name: x-namespace
                  in: header
                  description: Namespace.
                  required: true
                  type: string
                - name: x-group
                  in: header
                  description: Group.
                  required: false
                  type: string
                  default: ""
                - name: x-origin
                  in: header
                  description: origin for the configuration.
                  required: true
                  type: string
                - name: x-did
                  in: header
                  description: did for the Configuration
                  required: false
                  type: string
                - name: x-nonce
                  in: header
                  description: Proof challenge
                  required: false
                  type: string
                - name: DidConfigurationRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/DidConfiguration'
                    required:
                        - x-tenantid
            responses:
                "200":
                    description: OK response.
                    schema: {}
            schemes:
                - http
    /v1/did/document:
        get:
            tags:
                - signer
            summary: didDoc signer
            operationId: signer#didDoc
            parameters:
                - name: x-namespace
                  in: header
                  description: Namespace.
                  required: false
                  type: string
                  default: transit
                - name: x-group
                  in: header
                  description: Group.
                  required: false
                  type: string
                  default: ""
                - name: x-did
                  in: header
                  description: did which is used for controller and id
                  required: false
                  type: string
                  default: did:web:localhost%3A:8080
                - name: x-engine
                  in: header
                  description: Engine which shall be used. Eg transit or transit;kv or kv
                  required: false
                  type: string
                  default: transit
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DidResponse'
                        required:
                            - id
                            - controller
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/DidResponse'
                        required:
                            - id
                            - controller
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/DidResponse'
                        required:
                            - id
                            - controller
            schemes:
                - http
    /v1/did/list:
        get:
            tags:
                - signer
            summary: didList signer
            operationId: signer#didList
            parameters:
                - name: x-namespace
                  in: header
                  description: Namespace.
                  required: true
                  type: string
                - name: x-group
                  in: header
                  description: Group.
                  required: false
                  type: string
                  default: ""
                - name: x-engine
                  in: header
                  description: Engine which shall be used. Eg transit or transit;kv or kv
                  required: false
                  type: string
                  default: transit
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DidListResponse'
                        required:
                            - list
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/DidListResponse'
                        required:
                            - list
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/DidListResponse'
                        required:
                            - list
            schemes:
                - http
    /v1/jwk/{namespace}/{key}:
        get:
            tags:
                - signer
            summary: JwkPublicKey signer
            description: JwkPublicKey returns public key by name and namespace.
            operationId: signer#JwkPublicKey
            parameters:
                - name: namespace
                  in: path
                  description: Key namespace.
                  required: true
                  type: string
                - name: key
                  in: path
                  description: Key name.
                  required: true
                  type: string
                - name: JwkPublicKeyRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/JwkPublicKeyRequest'
                    required:
                        - group
            responses:
                "200":
                    description: OK response.
                    schema: {}
                "404":
                    description: Not Found response.
                    schema: {}
                "500":
                    description: Internal Server Error response.
                    schema: {}
            schemes:
                - http
    /v1/jwks:
        get:
            tags:
                - signer
            summary: Jwks signer
            operationId: signer#Jwks
            parameters:
                - name: x-namespace
                  in: header
                  description: Namespace.
                  required: true
                  type: string
                - name: x-group
                  in: header
                  description: Group.
                  required: false
                  type: string
                - name: x-engine
                  in: header
                  description: Engine which shall be used. Eg transit or transit;kv or kv
                  required: false
                  type: string
                  default: transit
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/JwksResponse'
                        required:
                            - keys
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/JwksResponse'
                        required:
                            - keys
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/JwksResponse'
                        required:
                            - keys
            schemes:
                - http
    /v1/namespaces:
        get:
            tags:
                - signer
            summary: Namespaces signer
            description: Namespaces returns all keys namespaces, which corresponds to enabled Vault transit engines.
            operationId: signer#Namespaces
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Voluptatem qui consequatur.
            schemes:
                - http
    /v1/namespaces/{namespace}/keys:
        get:
            tags:
                - signer
            summary: NamespaceKeys signer
            description: NamespaceKeys returns all keys in a given namespace.
            operationId: signer#NamespaceKeys
            parameters:
                - name: namespace
                  in: path
                  description: Namespace for signing keys.
                  required: true
                  type: string
                - name: x-group
                  in: header
                  description: Group identifies a group of keys within a namespace.
                  required: false
                  type: string
                  default: ""
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Aut pariatur.
            schemes:
                - http
    /v1/presentation:
        post:
            tags:
                - signer
            summary: CreatePresentation signer
            description: CreatePresentation creates VP with proof from raw JSON data.
            operationId: signer#CreatePresentation
            parameters:
                - name: CreatePresentationRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/CreatePresentationRequest'
                    required:
                        - namespace
                        - key
                        - data
            responses:
                "200":
                    description: OK response.
                    schema: {}
            schemes:
                - http
    /v1/presentation/proof:
        post:
            tags:
                - signer
            summary: PresentationProof signer
            description: PresentationProof adds a proof to a given Verifiable Presentation.
            operationId: signer#PresentationProof
            parameters:
                - name: PresentationProofRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/PresentationProofRequest'
                    required:
                        - namespace
                        - key
                        - presentation
            responses:
                "200":
                    description: OK response.
                    schema: {}
            schemes:
                - http
    /v1/presentation/verify:
        post:
            tags:
                - signer
            summary: VerifyPresentation signer
            description: VerifyPresentation verifies the proof of a Verifiable Presentation.
            operationId: signer#VerifyPresentation
            parameters:
                - name: x-format
                  in: header
                  description: format
                  required: false
                  type: string
                  default: ldp_vc
                  enum:
                    - ldp_vc
                    - dc+sd-jwt
                - name: VerifyPresentationRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VerifyPresentationRequest'
                    required:
                        - presentation
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/VerifyResult'
                        required:
                            - valid
            schemes:
                - http
    /v1/sign:
        post:
            tags:
                - signer
            summary: Sign signer
            description: Sign creates digital signature on base64 encoded binary data.
            operationId: signer#Sign
            parameters:
                - name: SignRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SignRequest'
                    required:
                        - namespace
                        - key
                        - data
                        - group
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SignResult'
                        required:
                            - signature
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/SignResult'
                        required:
                            - signature
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/SignResult'
                        required:
                            - signature
            schemes:
                - http
    /v1/verification-methods/{namespace}/{did}:
        get:
            tags:
                - signer
            summary: VerificationMethods signer
            description: VerificationMethods returns all public keys in a given namespace. The result is formatted as array of DID verification methods with their controller attribute being the given DID in the request.
            operationId: signer#VerificationMethods
            parameters:
                - name: namespace
                  in: path
                  description: Keys namespace.
                  required: true
                  type: string
                - name: did
                  in: path
                  description: DID controller of the keys.
                  required: true
                  type: string
                - name: VerificationMethodsRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VerificationMethodsRequest'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/DIDVerificationMethod'
            schemes:
                - http
    /v1/verification-methods/{namespace}/{key}/{did}:
        get:
            tags:
                - signer
            summary: VerificationMethod signer
            description: VerificationMethod returns a single public key formatted as DID verification method for a given namespace, key and did. When did:jwk is set for did, a did:jwk is generated from the key.
            operationId: signer#VerificationMethod
            parameters:
                - name: namespace
                  in: path
                  description: Key namespace.
                  required: true
                  type: string
                - name: key
                  in: path
                  description: Name of requested key.
                  required: true
                  type: string
                - name: did
                  in: path
                  description: DID controller of the key.
                  required: true
                  type: string
                - name: VerificationMethodRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VerificationMethodRequest'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DIDVerificationMethod'
                        required:
                            - id
                            - type
                            - controller
                            - publicKeyJwk
            schemes:
                - http
definitions:
    CreateCredentialRequest:
        title: CreateCredentialRequest
        type: object
        properties:
            context:
                type: array
                items:
                    type: string
                    example: Consequatur odit ut.
                description: Additional JSONLD contexts to be specified in the VC.
                example:
                    - https://w3id.org/security/suites/jws-2020/v1
                    - https://schema.org
            credentialSubject:
                description: Raw JSON that will be the VC subject.
                example:
                    hello: world
            disclosureFrame:
                type: array
                items:
                    type: string
                    example: Laudantium voluptatibus ipsam autem eligendi.
                description: Disclosed Attributes
                example:
                    - email
            format:
                type: string
                description: identifies the format of the credential.
                default: ldp_vc
                example: ldp_vc or dc+sd-jwt
                enum:
                    - ldp_vc
                    - dc+sd-jwt
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
            holder:
                type: string
                description: Holder Binding
                example: urn:3333:ddd
            issuer:
                type: string
                description: Issuer DID of the Verifiable Credential.
                example: did:web:example.com
            key:
                type: string
                description: Key to use for the proof signature.
                example: key1
            namespace:
                type: string
                description: Key namespace.
                example: transit
            nonce:
                type: string
                description: Proof challenge
                example: 3483492392vvv-fff
            signatureType:
                type: string
                description: Type of signature. For sd-jwt is it automatically selected.
                default: jsonwebsignature2020
                example: ed25519signature2020
                enum:
                    - ed25519signature2020
                    - jsonwebsignature2020
            status:
                type: boolean
                description: Append Status
                example: true
            statuslisttype:
                type: string
                description: Statuslist. Ignored when status=false
                default: StatusList2021
                example: urn:3333:ddd
            type:
                type: array
                items:
                    type: string
                    example: Iste nostrum numquam quaerat natus temporibus maxime.
                description: Type(s) of the credential. Just first one for sd-jwt used.
                example:
                    - VerifiableCredential
                    - TestCredential]
        example:
            context:
                - https://w3id.org/security/suites/jws-2020/v1
                - https://schema.org
            credentialSubject:
                hello: world
            disclosureFrame:
                - email
            format: ldp_vc or dc+sd-jwt
            group: Group
            holder: urn:3333:ddd
            issuer: did:web:example.com
            key: key1
            namespace: transit
            nonce: 3483492392vvv-fff
            signatureType: ed25519signature2020
            status: true
            statuslisttype: urn:3333:ddd
            type:
                - VerifiableCredential
                - TestCredential]
        required:
            - namespace
            - key
            - credentialSubject
    CreatePresentationRequest:
        title: CreatePresentationRequest
        type: object
        properties:
            context:
                type: array
                items:
                    type: string
                    example: Voluptas eos sed vero qui.
                description: Additional JSONLD contexts to be specified in the VP.
                example:
                    - https://w3id.org/security/suites/jws-2020/v1
                    - https://schema.org
            data:
                type: array
                items:
                    example: Eveniet et.
                description: Raw JSON to be included inside the VP as Verifiable Credential.
                example:
                    - hello: world
                    - hola: mundo
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
            issuer:
                type: string
                description: Issuer DID of the Verifiable Presentation.
                example: did:web:example.com
            key:
                type: string
                description: Key to use for the proof signature.
                example: key1
            namespace:
                type: string
                description: Key namespace.
                example: transit
            nonce:
                type: string
                description: Proof challenge
                example: 3483492392vvv-fff
            signatureType:
                type: string
                description: Type of signature. For sd-jwt is it automatically selected.
                default: jsonwebsignature2020
                example: ed25519signature2020
                enum:
                    - ed25519signature2020
                    - jsonwebsignature2020
        example:
            context:
                - https://w3id.org/security/suites/jws-2020/v1
                - https://schema.org
            data:
                - hello: world
                - hola: mundo
            group: Group
            issuer: did:web:example.com
            key: key1
            namespace: transit
            nonce: 3483492392vvv-fff
            signatureType: ed25519signature2020
        required:
            - namespace
            - key
            - data
    CredentialProofRequest:
        title: CredentialProofRequest
        type: object
        properties:
            credential:
                description: Verifiable Credential in JSON format or as sdjwt.
                example:
                    context:
                        - https://www.w3.org/2018/credentials/v1
                        - https://w3id.org/security/suites/jws-2020/v1
                        - https://schema.org
                    type:
                        - VerifiableCredential
                    issuer: did:web:nginx:policy:policy:example:example:1.0:evaluation
                    issuancedate: 2010-01-01T19:23:24.651387237Z
                    credentialsubject:
                        name: Alice
                        allow: true
            disclosureFrame:
                type: array
                items:
                    type: string
                    example: Porro facilis et molestias ut ea reiciendis.
                description: Disclosed Attributes
                example:
                    - email
            format:
                type: string
                description: identifies the format of the credential.
                default: ldp_vc
                example: ldp_vc or dc+sd-jwt
                enum:
                    - ldp_vc
                    - dc+sd-jwt
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
            holder:
                type: string
                description: Holder Binding
                example: urn:3333:ddd
            key:
                type: string
                description: Key to use for the proof signature (optional).
                example: key1
            namespace:
                type: string
                description: Key namespace.
                example: transit
            nonce:
                type: string
                description: Proof challenge
                example: 3483492392vvv-fff
            signatureType:
                type: string
                description: Type of signature.For sd-jwt is it automatically selected.
                default: jsonwebsignature2020
                example: ed25519signature2020
                enum:
                    - ed25519signature2020
                    - jsonwebsignature2020
            statuslisttype:
                type: string
                description: Statuslist. Ignored when status=false
                default: StatusList2021
                example: urn:3333:ddd
            x-did:
                type: string
                description: Did
                example: https://test
            x-groupid:
                type: string
                description: Tenant Group
                default: ""
                example: group1
            x-origin:
                type: string
                description: Origin of call
                example: https://test
            x-tenantid:
                type: string
                description: tenantid
                example: demotenant
        example:
            credential:
                context:
                    - https://www.w3.org/2018/credentials/v1
                    - https://w3id.org/security/suites/jws-2020/v1
                    - https://schema.org
                type:
                    - VerifiableCredential
                issuer: did:web:nginx:policy:policy:example:example:1.0:evaluation
                issuancedate: 2010-01-01T19:23:24.651387237Z
                credentialsubject:
                    name: Alice
                    allow: true
            disclosureFrame:
                - email
            format: ldp_vc or dc+sd-jwt
            group: Group
            holder: urn:3333:ddd
            key: key1
            namespace: transit
            nonce: 3483492392vvv-fff
            signatureType: ed25519signature2020
            statuslisttype: urn:3333:ddd
            x-did: https://test
            x-groupid: group1
            x-origin: https://test
            x-tenantid: demotenant
        required:
            - namespace
            - key
            - credential
            - x-tenantid
            - x-did
            - x-origin
    DIDVerificationMethod:
        title: DIDVerificationMethod
        type: object
        properties:
            controller:
                type: string
                description: Controller of verification method specified as DID.
                example: did:web:example.com
            id:
                type: string
                description: ID of verification method.
                example: key1
            publicKeyJwk:
                description: Public Key encoded in JWK format.
                example: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
            type:
                type: string
                description: Type of verification method key.
                example: JsonWebKey2020
        description: Public Key represented as DID Verification Method.
        example:
            controller: did:web:example.com
            id: key1
            publicKeyJwk: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
            type: JsonWebKey2020
        required:
            - id
            - type
            - controller
            - publicKeyJwk
    DidConfiguration:
        title: DidConfiguration
        type: object
        properties:
            x-groupid:
                type: string
                description: Tenant Group
                example: group1
            x-signatureType:
                type: string
                description: Type of signature
                default: jsonwebsignature2020
                example: ed25519signature2020
                enum:
                    - ed25519signature2020
                    - jsonwebsignature2020
            x-tenantid:
                type: string
                description: tenantid
                example: demotenant
        example:
            x-groupid: group1
            x-signatureType: ed25519signature2020
            x-tenantid: demotenant
        required:
            - x-tenantid
    DidListResponse:
        title: DidListResponse
        type: object
        properties:
            list:
                type: array
                items:
                    $ref: '#/definitions/DidListResponseItem'
                description: did jwk list of keys
                example:
                    - did: Unde facilis ut similique molestias aperiam quia.
                      name: Tempora et non aut inventore.
                    - did: Unde facilis ut similique molestias aperiam quia.
                      name: Tempora et non aut inventore.
                    - did: Unde facilis ut similique molestias aperiam quia.
                      name: Tempora et non aut inventore.
                    - did: Unde facilis ut similique molestias aperiam quia.
                      name: Tempora et non aut inventore.
        example:
            list:
                - did: Unde facilis ut similique molestias aperiam quia.
                  name: Tempora et non aut inventore.
                - did: Unde facilis ut similique molestias aperiam quia.
                  name: Tempora et non aut inventore.
                - did: Unde facilis ut similique molestias aperiam quia.
                  name: Tempora et non aut inventore.
                - did: Unde facilis ut similique molestias aperiam quia.
                  name: Tempora et non aut inventore.
        required:
            - list
    DidListResponseItem:
        title: DidListResponseItem
        type: object
        properties:
            did:
                type: string
                description: DID JWK of key
                example: Ullam rerum ea.
            name:
                type: string
                description: name of the key.
                example: Expedita nam nostrum fuga est dicta.
        example:
            did: Labore eum libero debitis tempore culpa illo.
            name: Placeat reprehenderit aperiam.
        required:
            - name
            - did
    DidResponse:
        title: DidResponse
        type: object
        properties:
            context:
                type: array
                items:
                    type: string
                    example: Quis soluta nihil expedita numquam.
                description: JSON-LD @context
                example:
                    - https://www.w3.org/ns/did/v1
            controller:
                type: string
                description: controler of the document
                example: Maxime harum omnis qui laborum.
            id:
                type: string
                description: did of the document
                example: In aliquid sint numquam facere sequi.
            service:
                type: array
                items:
                    $ref: '#/definitions/ServiceEndpoint'
                description: serviceendpoints
                example:
                    - id: Ducimus eum facere enim accusantium.
                      serviceEndpoint: Suscipit expedita quos eligendi.
                      type: Sint laudantium rerum neque.
                    - id: Ducimus eum facere enim accusantium.
                      serviceEndpoint: Suscipit expedita quos eligendi.
                      type: Sint laudantium rerum neque.
                    - id: Ducimus eum facere enim accusantium.
                      serviceEndpoint: Suscipit expedita quos eligendi.
                      type: Sint laudantium rerum neque.
            verificationMethod:
                type: array
                items:
                    $ref: '#/definitions/DIDVerificationMethod'
                description: methods of the document
                example:
                    - controller: did:web:example.com
                      id: key1
                      publicKeyJwk: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
                      type: JsonWebKey2020
                    - controller: did:web:example.com
                      id: key1
                      publicKeyJwk: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
                      type: JsonWebKey2020
        example:
            context:
                - https://www.w3.org/ns/did/v1
            controller: Ut at dolores omnis voluptas.
            id: Facilis ratione cumque in facilis.
            service:
                - id: Ducimus eum facere enim accusantium.
                  serviceEndpoint: Suscipit expedita quos eligendi.
                  type: Sint laudantium rerum neque.
                - id: Ducimus eum facere enim accusantium.
                  serviceEndpoint: Suscipit expedita quos eligendi.
                  type: Sint laudantium rerum neque.
            verificationMethod:
                - controller: did:web:example.com
                  id: key1
                  publicKeyJwk: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
                  type: JsonWebKey2020
                - controller: did:web:example.com
                  id: key1
                  publicKeyJwk: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
                  type: JsonWebKey2020
                - controller: did:web:example.com
                  id: key1
                  publicKeyJwk: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
                  type: JsonWebKey2020
                - controller: did:web:example.com
                  id: key1
                  publicKeyJwk: https://openid.net/specs/draft-jones-json-web-key-03.html#ExampleJWK
                  type: JsonWebKey2020
        required:
            - id
            - controller
    HealthResponse:
        title: HealthResponse
        type: object
        properties:
            service:
                type: string
                description: Service name.
                example: Tempora voluptatibus aperiam eius velit.
            status:
                type: string
                description: Status message.
                example: Dolores libero.
            version:
                type: string
                description: Service runtime version.
                example: Tempora voluptatem error molestiae.
        example:
            service: Deleniti laudantium exercitationem tenetur iusto eos quidem.
            status: Dolorum et consequatur sed in vero qui.
            version: Ut et quasi eius error minima eaque.
        required:
            - service
            - status
            - version
    JwkPublicKeyRequest:
        title: JwkPublicKeyRequest
        type: object
        properties:
            engine:
                type: string
                description: Engine which shall be used. Eg transit or transit;kv or kv
                default: transit
                example: transit
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
        example:
            engine: transit
            group: Group
        required:
            - group
    JwksResponse:
        title: JwksResponse
        type: object
        properties:
            keys:
                type: array
                items:
                    example: Praesentium est at esse laudantium ex aut.
                description: List of jwk
                example:
                    - Rem architecto.
                    - Quod et.
                    - Nihil nihil dicta non.
        example:
            keys:
                - Aut aspernatur corrupti esse ut.
                - Voluptatum labore id ducimus.
        required:
            - keys
    PresentationProofRequest:
        title: PresentationProofRequest
        type: object
        properties:
            aud:
                type: string
                description: audience
                example: http://...
            disclosureFrame:
                type: array
                items:
                    type: string
                    example: Fugit voluptatem maxime dolor et.
                description: Disclosed Attributes
                example:
                    - email
            format:
                type: string
                description: identifies the format of the credential.
                default: ldp_vc
                example: ldp_vc or dc+sd-jwt
                enum:
                    - ldp_vc
                    - dc+sd-jwt
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
            issuer:
                type: string
                description: Issuer DID used to specify proof verification info.
                example: Nihil numquam doloremque.
            key:
                type: string
                description: Key to use for the proof signature.
                example: key1
            namespace:
                type: string
                description: Key namespace.
                example: transit
            nonce:
                type: string
                description: Proof challenge
                example: 3483492392vvv-fff
            presentation:
                description: Verifiable Presentation in JSON format.
                example: Saepe quidem dolores fugiat.
            signatureType:
                type: string
                description: Type of signature.For sd-jwt is it automatically selected.
                default: jsonwebsignature2020
                example: ed25519signature2020
                enum:
                    - ed25519signature2020
                    - jsonwebsignature2020
                    - sdjwt
        example:
            aud: http://...
            disclosureFrame:
                - email
            format: ldp_vc or dc+sd-jwt
            group: Group
            issuer: Fugit quo voluptatem aut.
            key: key1
            namespace: transit
            nonce: 3483492392vvv-fff
            presentation: Unde blanditiis ea recusandae.
            signatureType: ed25519signature2020
        required:
            - namespace
            - key
            - presentation
    ServiceEndpoint:
        title: ServiceEndpoint
        type: object
        properties:
            id:
                type: string
                description: did of the document
                example: Eum quis.
            serviceEndpoint:
                type: string
                description: Endpoint URL
                example: Accusamus quisquam dolorem quibusdam cum nostrum aut.
            type:
                type: string
                description: type of endpoint
                example: Laudantium autem.
        example:
            id: Recusandae fugit ducimus assumenda omnis aut.
            serviceEndpoint: Suscipit molestiae a nihil voluptates rerum.
            type: Quaerat est cupiditate.
        required:
            - id
            - type
            - serviceEndpoint
    SignRequest:
        title: SignRequest
        type: object
        properties:
            data:
                type: string
                description: Data that must be signed, encoded as base64 string.
                example: Qui laboriosam.
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
            key:
                type: string
                description: Key to be used for signing.
                example: Eius corporis et.
            namespace:
                type: string
                description: Key namespace to be used for signing.
                example: Et sunt culpa est et accusantium sit.
        example:
            data: Facere doloribus quo eos.
            group: Group
            key: Maxime corrupti.
            namespace: Hic alias consectetur excepturi esse tenetur repellat.
        required:
            - namespace
            - key
            - data
            - group
    SignResult:
        title: SignResult
        type: object
        properties:
            signature:
                type: string
                description: Signature encoded as base64 string.
                example: Similique fuga iste aliquid quam.
        example:
            signature: Omnis quas perferendis id ipsum quis recusandae.
        required:
            - signature
    VerificationMethodRequest:
        title: VerificationMethodRequest
        type: object
        properties:
            engine:
                type: string
                description: Engine which shall be used. Eg transit or transit;kv or kv
                default: transit
                example: transit
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
        example:
            engine: transit
            group: Group
    VerificationMethodsRequest:
        title: VerificationMethodsRequest
        type: object
        properties:
            engine:
                type: string
                description: Engine which shall be used. Eg transit or transit;kv or kv
                default: transit
                example: transit
            group:
                type: string
                description: Group identifies a group of keys within a namespace.
                default: ""
                example: Group
        example:
            engine: transit
            group: Group
    VerifyCredentialRequest:
        title: VerifyCredentialRequest
        type: object
        properties:
            credential:
                type: string
                description: Verifiable Credential in JSON format.
                example:
                    - 86
                    - 101
                    - 110
                    - 105
                    - 97
                    - 109
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 109
                    - 32
                    - 113
                    - 117
                    - 105
                    - 32
                    - 102
                    - 117
                    - 103
                    - 105
                    - 116
                    - 46
                format: byte
            disclosureFrame:
                type: array
                items:
                    type: string
                    example: Ab doloremque.
                description: Disclosed Attributes
                example:
                    - email
        example:
            credential:
                - 65
                - 117
                - 116
                - 101
                - 109
                - 32
                - 99
                - 117
                - 109
                - 113
                - 117
                - 101
                - 32
                - 98
                - 101
                - 97
                - 116
                - 97
                - 101
                - 46
            disclosureFrame:
                - email
        required:
            - credential
    VerifyPresentationRequest:
        title: VerifyPresentationRequest
        type: object
        properties:
            aud:
                type: string
                description: expected audience
                example: Omnis est id sit delectus esse.
            disclosureFrame:
                type: array
                items:
                    type: string
                    example: Reiciendis ut et.
                description: Disclosed Attributes
                example:
                    - email
            nonce:
                type: string
                description: expected nonce
                example: Sapiente provident quo quis consectetur.
            presentation:
                type: string
                description: Verifiable Presentation in JSON or sdjwt format.
                example:
                    - 68
                    - 111
                    - 108
                    - 111
                    - 114
                    - 32
                    - 101
                    - 120
                    - 112
                    - 101
                    - 100
                    - 105
                    - 116
                    - 97
                    - 32
                    - 100
                    - 111
                    - 108
                    - 111
                    - 114
                    - 32
                    - 109
                    - 111
                    - 108
                    - 101
                    - 115
                    - 116
                    - 105
                    - 97
                    - 115
                    - 32
                    - 100
                    - 105
                    - 99
                    - 116
                    - 97
                    - 32
                    - 105
                    - 110
                    - 32
                    - 100
                    - 105
                    - 103
                    - 110
                    - 105
                    - 115
                    - 115
                    - 105
                    - 109
                    - 111
                    - 115
                    - 46
                format: byte
        example:
            aud: Voluptatem et quo vel eaque molestiae.
            disclosureFrame:
                - email
            nonce: Sed quia aspernatur consequuntur ducimus eos consequuntur.
            presentation:
                - 82
                - 97
                - 116
                - 105
                - 111
                - 110
                - 101
                - 32
                - 101
                - 117
                - 109
                - 46
        required:
            - presentation
    VerifyResult:
        title: VerifyResult
        type: object
        properties:
            disclosedCredential:
                description: Disclosed Credential
                example: Autem non aut quisquam sunt.
            valid:
                type: boolean
                description: Valid specifies if the proof is successfully verified.
                example: true
        example:
            disclosedCredential: Consequatur voluptatibus dignissimos autem rerum tempora.
            valid: false
        required:
            - valid
